inherit_from:
  - .rubocop_todo.yml
Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - config/**/*
    - db/**/*
    - script/rails
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/**/*
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/**/*
Style/RegexpLiteral:
  Exclude:
    - features/**/*
    - 'app/models/file_upload.rb'
Lint/Debugger:
  Exclude:
    - 'features/step_definitions/debug_steps.rb'
Lint/AssignmentInCondition:
  Exclude:
    - 'app/controllers/advisor/clients_controller.rb'
    - 'app/controllers/clients_controller.rb'
    - 'app/models/client.rb'
    - 'db/fixtures/seed_helper.rb'
Lint/ScriptPermission:
  Exclude:
    - 'Rakefile'
Style/ClassAndModuleChildren:
  Enabled: false
Lint/HandleExceptions:
  Exclude:
    - Rakefile
