AllCops:
  TargetRubyVersion: 2.4.1
Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - config/**/*
    - db/**/*
    - script/rails
    - features/step_definitions/referrer_steps.rb
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - features/step_definitions/referrer_steps.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/**/*
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/**/*
Style/RegexpLiteral:
  Exclude:
    - features/**/*
    - 'app/models/file_upload.rb'
Lint/Debugger:
  Exclude:
    - 'features/step_definitions/debug_steps.rb'
Lint/AssignmentInCondition:
  Exclude:
    - 'app/controllers/advisor/clients_controller.rb'
    - 'app/controllers/clients_controller.rb'
    - 'app/models/client.rb'
    - 'db/fixtures/seed_helper.rb'
Lint/ScriptPermission:
  Exclude:
    - 'Rakefile'
Style/ClassAndModuleChildren:
  Enabled: false
Lint/HandleExceptions:
  Exclude:
    - Rakefile
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Style/WordArray:
  Exclude:
    - 'db/schema.rb'
Metrics/AbcSize:
  Exclude:
    - 'features/support/*'
    - 'lib/seeders/*'
    - 'spec/helpers/*'
Rails/FilePath:
  Exclude:
    - 'lib/tasks/cucumber.rake'
Rails/Output:
  Exclude:
    - 'lib/seeders/client_seeder.rb'
Metrics/LineLength:
  Max: 166
Rails/OutputSafety:
  Exclude:
    - 'config/environment.rb'
Rails/SkipsModelValidations:
  Exclude:
    - 'lib/seeders/client_seeder.rb'
Metrics/AbcSize:
  Exclude:
    - features/step_definitions/referrer_steps.rb
