default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV['DATABASE_URL_STRING'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL_STRING'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL_STRING'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_STRING'] %>